experiment_name: rfe_10_features
model_name: Ridge
parameters:
  alpha: 0.1
  copy_X: true
  fit_intercept: true
  max_iter: null
  positive: false
  random_state: null
  solver: auto
  tol: 0.0001
target_variable: price
metrics:
  r2: 0.9940329798361337
  rmse: 16671.545902646503
  mae: 8162.0181091603845
features_used:
- sqft
- bathrooms
- house_age
- price_per_sqft
- bed_bath_ratio
- location_Downtown
- location_Suburb
- location_Urban
- location_Waterfront
- condition
